#!/bin/bash
echo "configuring pin 9.12 as an output..."
config-pin p9.12 gpio
echo "configuring pin 8.16 as pull up input..."
config-pin p8.16 gpio_pu
echo "done configuring"
echo "building the myGpio applications"
g++ -Wall myGpio.cpp myGpioApp.cpp -o myGpioApp -pthread
echo "Finished"
